---
- name: Install Emacs
  community.general.snap:
    name: emacs
    channel: stable
    classic: true
    state: present
  become: true

- name: Copy Emacs snap app launcher to ~/.local/share/applications/
  ansible.builtin.copy:
    src: /var/lib/snapd/desktop/applications/emacs_emacs.desktop
    dest: /home/cenouro/.local/share/applications/emacs_emacs.desktop
    mode: preserve
    force: false

- name: Customize Emacs app launcher
  ansible.builtin.lineinfile:
    path: /home/cenouro/.local/share/applications/emacs_emacs.desktop
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    firstmatch: true
    backrefs: true
  loop:
    - regexp: '^Exec=(.*)/snap/bin/emacs(?!\s*--maximized)(.*)$'
      line: 'Exec=\1/snap/bin/emacs --maximized\2'
    - regexp: '^Icon=/snap/emacs/(?!current).*?/(.*)$'
      line: 'Icon=/snap/emacs/current/\1'

- name: Disable startup notification
  ansible.builtin.lineinfile:
    path: /home/cenouro/.local/share/applications/emacs_emacs.desktop
    line: '{{ item.line }}'
    state: '{{ item.state }}'
  loop:
    - line: StartupNotify=true
      state: absent
    - line: StartupNotify=false
      state: present
    - line: StartupWMClass=Emacs
      state: present

- name: Copy Emacs (Client) snap app launcher to ~/.local/share/applications/
  ansible.builtin.copy:
    src: /var/lib/snapd/desktop/applications/emacs_emacsclient.desktop
    dest: /home/cenouro/.local/share/applications/emacs_emacsclient.desktop
    mode: preserve
    force: false

- name: Disable Emacs (Client)
  ansible.builtin.lineinfile:
    path: /home/cenouro/.local/share/applications/emacs_emacsclient.desktop
    line: Hidden=true
    state: present
    insertafter: 'Name=Emacs \(Client\)'
    firstmatch: true
...
