---
- name: Install Emacs
  community.general.snap:
    name: emacs
    channel: stable
    classic: true
    state: present
  become: true

- name: Copy Emacs snap app launcher to ~/.local/share/applications/
  ansible.builtin.copy:
    src: /var/lib/snapd/desktop/applications/emacs_emacs.desktop
    dest: /home/cenouro/.local/share/applications/emacs_emacs.desktop
    mode: preserve
    force: false

- name: Customize Emacs app launcher
  ansible.builtin.lineinfile:
    path: /home/cenouro/.local/share/applications/emacs_emacs.desktop
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    firstmatch: true
    backrefs: true
  loop:
    - regexp: '^Exec=(.*)/snap/bin/emacs(?!\s*--maximized)(.*)$'
      line: 'Exec=\1/snap/bin/emacs --maximized\2'
    - regexp: '^Icon=/snap/emacs/(?!current).*?/(.*)$'
      line: 'Icon=/snap/emacs/current/\1'
...
