---
- name: Install Emacs
  community.general.snap:
    name: emacs
    channel: stable
    classic: true
    state: present
  become: yes

- name: Install packages for native compilation
  ansible.builtin.apt:
    pkg:
      - gcc-10
      - libgccjit-10-dev
      - libgccjit0
      - libjansson-dev
      - libjansson4
    state: present
  become: yes

- name: Install JetBrains Mono
  ansible.builtin.apt:
    pkg: fonts-jetbrains-mono
    state: present
  become: yes
...
