---
- name: Fix prompt problems with inf-ruby.el
  ansible.builtin.blockinfile:
    path: ~/.irbrc
    block: |
      IRB.conf[:USE_MULTILINE] = false if ENV['INSIDE_EMACS']
      IRB.conf[:USE_READLINE] = false if ENV['INSIDE_EMACS']
    marker_begin: BEGIN
    marker_end: END
    marker: '# ANSIBLE {mark}: fix prompt problems with inf-ruby.el'
    create: true
...
