---
- name: Install Emacs
  community.general.snap:
    name: emacs
    channel: stable
    classic: true
    state: present
  become: true

- name: Install packages for native compilation
  ansible.builtin.apt:
    pkg:
      - gcc-10
      - libgccjit-10-dev
      - libgccjit0
      - libjansson-dev
      - libjansson4
    state: present
  become: true

- name: Install JetBrains Mono
  ansible.builtin.apt:
    pkg: fonts-jetbrains-mono
    state: present
  become: true

- name: Ensure Emacs directory
  ansible.builtin.file:
    dest: '{{ emacs_d }}'
    state: directory

- name: Link assets
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - '{{ init_el }}'
    - '{{ elisp }}'

- name: Create custom.el
  ansible.builtin.shell:
    cmd: touch '{{ custom_el }}'
    creates: '{{ custom_el }}'
...
