---
- name: Install JetBrains Mono
  ansible.builtin.package:
    name: "{{ lookup('ansible.builtin.vars', DISTRO + '_jetbrains_mono_fonts') }}"
    state: present
  become: true

- name: Ensure Emacs directory
  ansible.builtin.file:
    dest: '{{ emacs_d }}'
    state: directory

- name: Link assets
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - '{{ init_el }}'
    - '{{ elisp }}'

- name: Create empty custom.el
  ansible.builtin.file:
    path: '{{ custom_el }}'
    state: touch
    access_time: preserve
    modification_time: preserve

- name: Include inf-ruby.yml
  include_tasks: inf-ruby.yml
...
